---
http_interactions:
- request:
    method: get
    uri: https://iad.servers.api.rackspacecloud.com/v2/<RS_TENANT_ID>/servers
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      X-Auth-Token:
      - AAD276xqrvGhMUmPG6eUoH7vF_x_juuKjGjDKRQQzabDXsCvxP9bhhbcPU0BShAbtYMSH4Lu-dFNROuq08bbR4KVJuz1yqNw3Z_m34F0F8yZgTcvVWhPkKYD-bHWIUD-sFq7hlUBagNMrw
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 27 Jan 2016 19:42:07 GMT
      - Wed, 27 Jan 2016 19:42:07 GMT
      Via:
      - 1.1 Repose (Repose/7.1.3.0)
      X-Trans-Id:
      - 919bccb7-8176-4798-93db-a5741c0a152d
      Content-Type:
      - application/json
      X-Compute-Request-Id:
      - req-4538cf63-be6a-4f31-9073-9527774e2839
      Content-Length:
      - '2705'
      Server:
      - Jetty(9.2.z-SNAPSHOT)
    body:
      encoding: UTF-8
      string: '{"servers": [{"id": "b2bfa0ed-5a9c-40d1-a43e-0a41f31ff413", "links":
        [{"href": "https://iad.servers.api.rackspacecloud.com/v2/<RS_TENANT_ID>/servers/b2bfa0ed-5a9c-40d1-a43e-0a41f31ff413",
        "rel": "self"}, {"href": "https://iad.servers.api.rackspacecloud.com/<RS_TENANT_ID>/servers/b2bfa0ed-5a9c-40d1-a43e-0a41f31ff413",
        "rel": "bookmark"}], "name": "Testing"}, {"id": "a0606809-bac8-4a51-8480-668c33072e2a",
        "links": [{"href": "https://iad.servers.api.rackspacecloud.com/v2/<RS_TENANT_ID>/servers/a0606809-bac8-4a51-8480-668c33072e2a",
        "rel": "self"}, {"href": "https://iad.servers.api.rackspacecloud.com/<RS_TENANT_ID>/servers/a0606809-bac8-4a51-8480-668c33072e2a",
        "rel": "bookmark"}], "name": "Testing"}, {"id": "95d4f801-858a-4728-9ac0-dc5900d71f76",
        "links": [{"href": "https://iad.servers.api.rackspacecloud.com/v2/<RS_TENANT_ID>/servers/95d4f801-858a-4728-9ac0-dc5900d71f76",
        "rel": "self"}, {"href": "https://iad.servers.api.rackspacecloud.com/<RS_TENANT_ID>/servers/95d4f801-858a-4728-9ac0-dc5900d71f76",
        "rel": "bookmark"}], "name": "crb_discourse"}, {"id": "b32068b7-4e57-4125-9d1a-33918e292e88",
        "links": [{"href": "https://iad.servers.api.rackspacecloud.com/v2/<RS_TENANT_ID>/servers/b32068b7-4e57-4125-9d1a-33918e292e88",
        "rel": "self"}, {"href": "https://iad.servers.api.rackspacecloud.com/<RS_TENANT_ID>/servers/b32068b7-4e57-4125-9d1a-33918e292e88",
        "rel": "bookmark"}], "name": "personal"}, {"id": "9037d915-ee27-4573-808b-167ddf05f856",
        "links": [{"href": "https://iad.servers.api.rackspacecloud.com/v2/<RS_TENANT_ID>/servers/9037d915-ee27-4573-808b-167ddf05f856",
        "rel": "self"}, {"href": "https://iad.servers.api.rackspacecloud.com/<RS_TENANT_ID>/servers/9037d915-ee27-4573-808b-167ddf05f856",
        "rel": "bookmark"}], "name": "CarinaCommunityDB2"}, {"id": "f1f0af61-fecd-4ed7-874d-3b6f5c591bdd",
        "links": [{"href": "https://iad.servers.api.rackspacecloud.com/v2/<RS_TENANT_ID>/servers/f1f0af61-fecd-4ed7-874d-3b6f5c591bdd",
        "rel": "self"}, {"href": "https://iad.servers.api.rackspacecloud.com/<RS_TENANT_ID>/servers/f1f0af61-fecd-4ed7-874d-3b6f5c591bdd",
        "rel": "bookmark"}], "name": "CarinaRedis"}, {"id": "a0eaa1df-592b-4637-a808-b5fe3cbe4250",
        "links": [{"href": "https://iad.servers.api.rackspacecloud.com/v2/<RS_TENANT_ID>/servers/a0eaa1df-592b-4637-a808-b5fe3cbe4250",
        "rel": "self"}, {"href": "https://iad.servers.api.rackspacecloud.com/<RS_TENANT_ID>/servers/a0eaa1df-592b-4637-a808-b5fe3cbe4250",
        "rel": "bookmark"}], "name": "CarinaCommunityDB1"}, {"id": "917185a6-ea7c-4bae-8954-f58b39b8b7f2",
        "links": [{"href": "https://iad.servers.api.rackspacecloud.com/v2/<RS_TENANT_ID>/servers/917185a6-ea7c-4bae-8954-f58b39b8b7f2",
        "rel": "self"}, {"href": "https://iad.servers.api.rackspacecloud.com/<RS_TENANT_ID>/servers/917185a6-ea7c-4bae-8954-f58b39b8b7f2",
        "rel": "bookmark"}], "name": "github_teams_guard"}]}'
    http_version: 
  recorded_at: Wed, 27 Jan 2016 19:42:08 GMT
- request:
    method: put
    uri: https://iad.servers.api.rackspacecloud.com/v2/<RS_TENANT_ID>/servers/b2bfa0ed-5a9c-40d1-a43e-0a41f31ff413
    body:
      encoding: UTF-8
      string: '{"server":{"id":"b2bfa0ed-5a9c-40d1-a43e-0a41f31ff413","links":[{"href":"https://iad.servers.api.rackspacecloud.com/v2/<RS_TENANT_ID>/servers/b2bfa0ed-5a9c-40d1-a43e-0a41f31ff413","rel":"self"},{"href":"https://iad.servers.api.rackspacecloud.com/<RS_TENANT_ID>/servers/b2bfa0ed-5a9c-40d1-a43e-0a41f31ff413","rel":"bookmark"}],"name":"Testing"}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      X-Auth-Token:
      - AAD276xqrvGhMUmPG6eUoH7vF_x_juuKjGjDKRQQzabDXsCvxP9bhhbcPU0BShAbtYMSH4Lu-dFNROuq08bbR4KVJuz1yqNw3Z_m34F0F8yZgTcvVWhPkKYD-bHWIUD-sFq7hlUBagNMrw
      Content-Type:
      - application/json
      Content-Length:
      - '328'
      User-Agent:
      - Ruby
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Date:
      - Wed, 27 Jan 2016 19:42:14 GMT
      Via:
      - 1.1 Repose (Repose/7.1.3.0)
      Www-Authenticate:
      - Keystone uri=https://identity.api.rackspacecloud.com/v2.0
      X-Trans-Id:
      - 787bbcdf-a29a-4a4c-a9de-a22aa3f8c078
      Content-Length:
      - '0'
      Server:
      - Jetty(9.2.z-SNAPSHOT)
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 27 Jan 2016 19:42:14 GMT
recorded_with: VCR 3.0.1
